# Generated by Django 4.2.2 on 2023-07-23 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_userprofile_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_profile',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_profile',
            new_name='profile',
        ),
    ]
